### ISSUE TITLE
Could not pass event PlayerInteractEvent to TARDIS

### ISSUE THREAD

**Issue by NanoTrasen-Inc** [eccentricdevotion/TARDIS#369]
**Bug Description**
`Could not pass event PlayerInteractEvent to TARDIS` errors are generated upon login, and upon performing other common actions like shift right clicking a sonic screwdriver in the air for the first time.

Possibly also related to this issue: https://discordapp.com/channels/693995819841617960/693997248547258438/769379084852527165

**Steps to Reproduce**
1. Install the latest version of Paper
2. Install TARDIS and ChunkGenerator plugin
3. Start and join the server
4. View console
5. See error

**Video**
https://www.youtube.com/watch?v=DLwbXOmy63o

**Server Log**
https://pastebin.com/kV9rdcAU

**`/tardis version` output**
```
[01:24:42 INFO]: [TARDIS] Server version: git-Paper-246 (MC: 1.16.3)
[01:24:42 INFO]: [TARDIS] TARDIS version: 4.5.3-b2205
[01:24:42 INFO]: [TARDIS] TARDISChunkGenerator version: 4.5.3
[01:24:42 INFO]: [TARDIS] Checking for new TARDIS builds...
```

**Comment by eccentricdevotion** [comment]
Restart server should fix it, but it shouldn't be happening for fresh installs - I'll look into it...

**Comment by NanoTrasen-Inc** [comment]
Still getting a NullPointerException when shift+right clicking a Sonic Screwdriver in the air for the first time.

See video:
https://www.youtube.com/watch?v=0SjM0wrG3SI

**Comment by NanoTrasen-Inc** [comment]
@eccentricdevotion 
@mentioning you because I don't know if Github sends notifications about closed issues.
